fragment HomeParts on Home {
  title
}

fragment AboutParts on About {
  description
}

fragment StructureParts on Structure {
  first_violins {
    __typename
    name
    concert
  }
  second_violins {
    __typename
    name
  }
  viols {
    __typename
    name
  }
  violoncellos {
    __typename
    name
  }
  basses {
    __typename
    name
  }
  flutes {
    __typename
    name
  }
  oboes {
    __typename
    name
  }
  clarinets {
    __typename
    name
  }
  bassoons {
    __typename
    name
  }
  french_horns {
    __typename
    name
  }
  trumpets {
    __typename
    name
  }
  trombones {
    __typename
    name
  }
  tube {
    __typename
    name
  }
  drums {
    __typename
    name
  }
}

fragment ConductorsParts on Conductors {
  conductors {
    __typename
    photo
    name
    text
  }
}

fragment ConcertParts on Concert {
  name
  date
  time
  address
  conductor
  solists
  price
  description
}

fragment GalleryParts on Gallery {
  sections {
    __typename
    name
    items {
      __typename
      url
    }
  }
}

fragment ContactParts on Contact {
  email
  leadership {
    __typename
    name
    phone
    email
  }
  practice {
    __typename
    text
    address
  }
}
