//@ts-nocheck
// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
import { gql } from 'tinacms';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String'];
  basename: Scalars['String'];
  breadcrumbs: Array<Scalars['String']>;
  path: Scalars['String'];
  relativePath: Scalars['String'];
  extension: Scalars['String'];
  template: Scalars['String'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean'];
  hasNextPage: Scalars['Boolean'];
  startCursor: Scalars['String'];
  endCursor: Scalars['String'];
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  sys?: Maybe<SystemInfo>;
  id: Scalars['ID'];
  form: Scalars['JSON'];
  values: Scalars['JSON'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float'];
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']>;
  getCollection: Collection;
  getCollections: Array<Collection>;
  node: Node;
  getDocument: DocumentNode;
  getDocumentList: DocumentConnection;
  getDocumentFields: Scalars['JSON'];
  getHomeDocument: HomeDocument;
  getHomeList: HomeConnection;
  getAboutDocument: AboutDocument;
  getAboutList: AboutConnection;
  getStructureDocument: StructureDocument;
  getStructureList: StructureConnection;
  getConductorsDocument: ConductorsDocument;
  getConductorsList: ConductorsConnection;
  getConcertDocument: ConcertDocument;
  getConcertList: ConcertConnection;
  getGalleryDocument: GalleryDocument;
  getGalleryList: GalleryConnection;
  getContactDocument: ContactDocument;
  getContactList: ContactConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String'];
};


export type QueryGetCollectionArgs = {
  collection?: InputMaybe<Scalars['String']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']>;
};


export type QueryGetDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGetDocumentListArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};


export type QueryGetHomeDocumentArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGetHomeListArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};


export type QueryGetAboutDocumentArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGetAboutListArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};


export type QueryGetStructureDocumentArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGetStructureListArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};


export type QueryGetConductorsDocumentArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGetConductorsListArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};


export type QueryGetConcertDocumentArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGetConcertListArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};


export type QueryGetGalleryDocumentArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGetGalleryListArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};


export type QueryGetContactDocumentArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGetContactListArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String'];
  slug: Scalars['String'];
  label?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  matches?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};

export type DocumentNode = HomeDocument | AboutDocument | StructureDocument | ConductorsDocument | ConcertDocument | GalleryDocument | ContactDocument;

export type Home = {
  __typename?: 'Home';
  title?: Maybe<Scalars['String']>;
};

export type HomeDocument = Node & Document & {
  __typename?: 'HomeDocument';
  id: Scalars['ID'];
  sys: SystemInfo;
  data: Home;
  form: Scalars['JSON'];
  values: Scalars['JSON'];
  dataJSON: Scalars['JSON'];
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<HomeDocument>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type About = {
  __typename?: 'About';
  description?: Maybe<Scalars['JSON']>;
};

export type AboutDocument = Node & Document & {
  __typename?: 'AboutDocument';
  id: Scalars['ID'];
  sys: SystemInfo;
  data: About;
  form: Scalars['JSON'];
  values: Scalars['JSON'];
  dataJSON: Scalars['JSON'];
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<AboutDocument>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type StructureFirst_Violins = {
  __typename?: 'StructureFirst_violins';
  name?: Maybe<Scalars['String']>;
};

export type StructureSecond_Violins = {
  __typename?: 'StructureSecond_violins';
  name?: Maybe<Scalars['String']>;
};

export type StructureViols = {
  __typename?: 'StructureViols';
  name?: Maybe<Scalars['String']>;
};

export type StructureVioloncellos = {
  __typename?: 'StructureVioloncellos';
  name?: Maybe<Scalars['String']>;
};

export type StructureBasses = {
  __typename?: 'StructureBasses';
  name?: Maybe<Scalars['String']>;
};

export type StructureFlutes = {
  __typename?: 'StructureFlutes';
  name?: Maybe<Scalars['String']>;
};

export type StructureOboes = {
  __typename?: 'StructureOboes';
  name?: Maybe<Scalars['String']>;
};

export type StructureClarinets = {
  __typename?: 'StructureClarinets';
  name?: Maybe<Scalars['String']>;
};

export type StructureBassoons = {
  __typename?: 'StructureBassoons';
  name?: Maybe<Scalars['String']>;
};

export type StructureFrench_Horns = {
  __typename?: 'StructureFrench_horns';
  name?: Maybe<Scalars['String']>;
};

export type StructureTrumpets = {
  __typename?: 'StructureTrumpets';
  name?: Maybe<Scalars['String']>;
};

export type StructureTrombones = {
  __typename?: 'StructureTrombones';
  name?: Maybe<Scalars['String']>;
};

export type StructureTube = {
  __typename?: 'StructureTube';
  name?: Maybe<Scalars['String']>;
};

export type StructureDrums = {
  __typename?: 'StructureDrums';
  name?: Maybe<Scalars['String']>;
};

export type Structure = {
  __typename?: 'Structure';
  first_violins?: Maybe<Array<Maybe<StructureFirst_Violins>>>;
  second_violins?: Maybe<Array<Maybe<StructureSecond_Violins>>>;
  viols?: Maybe<Array<Maybe<StructureViols>>>;
  violoncellos?: Maybe<Array<Maybe<StructureVioloncellos>>>;
  basses?: Maybe<Array<Maybe<StructureBasses>>>;
  flutes?: Maybe<Array<Maybe<StructureFlutes>>>;
  oboes?: Maybe<Array<Maybe<StructureOboes>>>;
  clarinets?: Maybe<Array<Maybe<StructureClarinets>>>;
  bassoons?: Maybe<Array<Maybe<StructureBassoons>>>;
  french_horns?: Maybe<Array<Maybe<StructureFrench_Horns>>>;
  trumpets?: Maybe<Array<Maybe<StructureTrumpets>>>;
  trombones?: Maybe<Array<Maybe<StructureTrombones>>>;
  tube?: Maybe<Array<Maybe<StructureTube>>>;
  drums?: Maybe<Array<Maybe<StructureDrums>>>;
};

export type StructureDocument = Node & Document & {
  __typename?: 'StructureDocument';
  id: Scalars['ID'];
  sys: SystemInfo;
  data: Structure;
  form: Scalars['JSON'];
  values: Scalars['JSON'];
  dataJSON: Scalars['JSON'];
};

export type StructureConnectionEdges = {
  __typename?: 'StructureConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<StructureDocument>;
};

export type StructureConnection = Connection & {
  __typename?: 'StructureConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<StructureConnectionEdges>>>;
};

export type ConductorsConductors = {
  __typename?: 'ConductorsConductors';
  photo?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  text?: Maybe<Scalars['String']>;
};

export type Conductors = {
  __typename?: 'Conductors';
  conductors?: Maybe<Array<Maybe<ConductorsConductors>>>;
};

export type ConductorsDocument = Node & Document & {
  __typename?: 'ConductorsDocument';
  id: Scalars['ID'];
  sys: SystemInfo;
  data: Conductors;
  form: Scalars['JSON'];
  values: Scalars['JSON'];
  dataJSON: Scalars['JSON'];
};

export type ConductorsConnectionEdges = {
  __typename?: 'ConductorsConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<ConductorsDocument>;
};

export type ConductorsConnection = Connection & {
  __typename?: 'ConductorsConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<ConductorsConnectionEdges>>>;
};

export type Concert = {
  __typename?: 'Concert';
  name?: Maybe<Scalars['String']>;
  date?: Maybe<Scalars['String']>;
  time?: Maybe<Scalars['String']>;
  address?: Maybe<Scalars['String']>;
  conductor?: Maybe<Scalars['String']>;
  solists?: Maybe<Scalars['String']>;
  price?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['JSON']>;
};

export type ConcertDocument = Node & Document & {
  __typename?: 'ConcertDocument';
  id: Scalars['ID'];
  sys: SystemInfo;
  data: Concert;
  form: Scalars['JSON'];
  values: Scalars['JSON'];
  dataJSON: Scalars['JSON'];
};

export type ConcertConnectionEdges = {
  __typename?: 'ConcertConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<ConcertDocument>;
};

export type ConcertConnection = Connection & {
  __typename?: 'ConcertConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<ConcertConnectionEdges>>>;
};

export type GallerySectionsItems = {
  __typename?: 'GallerySectionsItems';
  url?: Maybe<Scalars['String']>;
};

export type GallerySections = {
  __typename?: 'GallerySections';
  name?: Maybe<Scalars['String']>;
  items?: Maybe<Array<Maybe<GallerySectionsItems>>>;
};

export type Gallery = {
  __typename?: 'Gallery';
  sections?: Maybe<Array<Maybe<GallerySections>>>;
};

export type GalleryDocument = Node & Document & {
  __typename?: 'GalleryDocument';
  id: Scalars['ID'];
  sys: SystemInfo;
  data: Gallery;
  form: Scalars['JSON'];
  values: Scalars['JSON'];
  dataJSON: Scalars['JSON'];
};

export type GalleryConnectionEdges = {
  __typename?: 'GalleryConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<GalleryDocument>;
};

export type GalleryConnection = Connection & {
  __typename?: 'GalleryConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<GalleryConnectionEdges>>>;
};

export type ContactLeadership = {
  __typename?: 'ContactLeadership';
  name?: Maybe<Scalars['String']>;
  phone?: Maybe<Scalars['String']>;
  email?: Maybe<Scalars['String']>;
};

export type ContactPractice = {
  __typename?: 'ContactPractice';
  text?: Maybe<Scalars['String']>;
  address?: Maybe<Scalars['String']>;
};

export type Contact = {
  __typename?: 'Contact';
  email?: Maybe<Scalars['String']>;
  leadership?: Maybe<ContactLeadership>;
  practice?: Maybe<ContactPractice>;
};

export type ContactDocument = Node & Document & {
  __typename?: 'ContactDocument';
  id: Scalars['ID'];
  sys: SystemInfo;
  data: Contact;
  form: Scalars['JSON'];
  values: Scalars['JSON'];
  dataJSON: Scalars['JSON'];
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<ContactDocument>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updateHomeDocument: HomeDocument;
  createHomeDocument: HomeDocument;
  updateAboutDocument: AboutDocument;
  createAboutDocument: AboutDocument;
  updateStructureDocument: StructureDocument;
  createStructureDocument: StructureDocument;
  updateConductorsDocument: ConductorsDocument;
  createConductorsDocument: ConductorsDocument;
  updateConcertDocument: ConcertDocument;
  createConcertDocument: ConcertDocument;
  updateGalleryDocument: GalleryDocument;
  createGalleryDocument: GalleryDocument;
  updateContactDocument: ContactDocument;
  createContactDocument: ContactDocument;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  template?: InputMaybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationUpdateHomeDocumentArgs = {
  relativePath: Scalars['String'];
  params: HomeMutation;
};


export type MutationCreateHomeDocumentArgs = {
  relativePath: Scalars['String'];
  params: HomeMutation;
};


export type MutationUpdateAboutDocumentArgs = {
  relativePath: Scalars['String'];
  params: AboutMutation;
};


export type MutationCreateAboutDocumentArgs = {
  relativePath: Scalars['String'];
  params: AboutMutation;
};


export type MutationUpdateStructureDocumentArgs = {
  relativePath: Scalars['String'];
  params: StructureMutation;
};


export type MutationCreateStructureDocumentArgs = {
  relativePath: Scalars['String'];
  params: StructureMutation;
};


export type MutationUpdateConductorsDocumentArgs = {
  relativePath: Scalars['String'];
  params: ConductorsMutation;
};


export type MutationCreateConductorsDocumentArgs = {
  relativePath: Scalars['String'];
  params: ConductorsMutation;
};


export type MutationUpdateConcertDocumentArgs = {
  relativePath: Scalars['String'];
  params: ConcertMutation;
};


export type MutationCreateConcertDocumentArgs = {
  relativePath: Scalars['String'];
  params: ConcertMutation;
};


export type MutationUpdateGalleryDocumentArgs = {
  relativePath: Scalars['String'];
  params: GalleryMutation;
};


export type MutationCreateGalleryDocumentArgs = {
  relativePath: Scalars['String'];
  params: GalleryMutation;
};


export type MutationUpdateContactDocumentArgs = {
  relativePath: Scalars['String'];
  params: ContactMutation;
};


export type MutationCreateContactDocumentArgs = {
  relativePath: Scalars['String'];
  params: ContactMutation;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  structure?: InputMaybe<StructureMutation>;
  conductors?: InputMaybe<ConductorsMutation>;
  concert?: InputMaybe<ConcertMutation>;
  gallery?: InputMaybe<GalleryMutation>;
  contact?: InputMaybe<ContactMutation>;
};

export type HomeMutation = {
  title?: InputMaybe<Scalars['String']>;
};

export type AboutMutation = {
  description?: InputMaybe<Scalars['JSON']>;
};

export type StructureFirst_ViolinsMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureSecond_ViolinsMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureViolsMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureVioloncellosMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureBassesMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureFlutesMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureOboesMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureClarinetsMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureBassoonsMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureFrench_HornsMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureTrumpetsMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureTrombonesMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureTubeMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureDrumsMutation = {
  name?: InputMaybe<Scalars['String']>;
};

export type StructureMutation = {
  first_violins?: InputMaybe<Array<InputMaybe<StructureFirst_ViolinsMutation>>>;
  second_violins?: InputMaybe<Array<InputMaybe<StructureSecond_ViolinsMutation>>>;
  viols?: InputMaybe<Array<InputMaybe<StructureViolsMutation>>>;
  violoncellos?: InputMaybe<Array<InputMaybe<StructureVioloncellosMutation>>>;
  basses?: InputMaybe<Array<InputMaybe<StructureBassesMutation>>>;
  flutes?: InputMaybe<Array<InputMaybe<StructureFlutesMutation>>>;
  oboes?: InputMaybe<Array<InputMaybe<StructureOboesMutation>>>;
  clarinets?: InputMaybe<Array<InputMaybe<StructureClarinetsMutation>>>;
  bassoons?: InputMaybe<Array<InputMaybe<StructureBassoonsMutation>>>;
  french_horns?: InputMaybe<Array<InputMaybe<StructureFrench_HornsMutation>>>;
  trumpets?: InputMaybe<Array<InputMaybe<StructureTrumpetsMutation>>>;
  trombones?: InputMaybe<Array<InputMaybe<StructureTrombonesMutation>>>;
  tube?: InputMaybe<Array<InputMaybe<StructureTubeMutation>>>;
  drums?: InputMaybe<Array<InputMaybe<StructureDrumsMutation>>>;
};

export type ConductorsConductorsMutation = {
  photo?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
  text?: InputMaybe<Scalars['String']>;
};

export type ConductorsMutation = {
  conductors?: InputMaybe<Array<InputMaybe<ConductorsConductorsMutation>>>;
};

export type ConcertMutation = {
  name?: InputMaybe<Scalars['String']>;
  date?: InputMaybe<Scalars['String']>;
  time?: InputMaybe<Scalars['String']>;
  address?: InputMaybe<Scalars['String']>;
  conductor?: InputMaybe<Scalars['String']>;
  solists?: InputMaybe<Scalars['String']>;
  price?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['JSON']>;
};

export type GallerySectionsItemsMutation = {
  url?: InputMaybe<Scalars['String']>;
};

export type GallerySectionsMutation = {
  name?: InputMaybe<Scalars['String']>;
  items?: InputMaybe<Array<InputMaybe<GallerySectionsItemsMutation>>>;
};

export type GalleryMutation = {
  sections?: InputMaybe<Array<InputMaybe<GallerySectionsMutation>>>;
};

export type ContactLeadershipMutation = {
  name?: InputMaybe<Scalars['String']>;
  phone?: InputMaybe<Scalars['String']>;
  email?: InputMaybe<Scalars['String']>;
};

export type ContactPracticeMutation = {
  text?: InputMaybe<Scalars['String']>;
  address?: InputMaybe<Scalars['String']>;
};

export type ContactMutation = {
  email?: InputMaybe<Scalars['String']>;
  leadership?: InputMaybe<ContactLeadershipMutation>;
  practice?: InputMaybe<ContactPracticeMutation>;
};

export type HomePartsFragment = { __typename?: 'Home', title?: string | null };

export type AboutPartsFragment = { __typename?: 'About', description?: any | null };

export type StructurePartsFragment = { __typename?: 'Structure', first_violins?: Array<{ __typename: 'StructureFirst_violins', name?: string | null } | null> | null, second_violins?: Array<{ __typename: 'StructureSecond_violins', name?: string | null } | null> | null, viols?: Array<{ __typename: 'StructureViols', name?: string | null } | null> | null, violoncellos?: Array<{ __typename: 'StructureVioloncellos', name?: string | null } | null> | null, basses?: Array<{ __typename: 'StructureBasses', name?: string | null } | null> | null, flutes?: Array<{ __typename: 'StructureFlutes', name?: string | null } | null> | null, oboes?: Array<{ __typename: 'StructureOboes', name?: string | null } | null> | null, clarinets?: Array<{ __typename: 'StructureClarinets', name?: string | null } | null> | null, bassoons?: Array<{ __typename: 'StructureBassoons', name?: string | null } | null> | null, french_horns?: Array<{ __typename: 'StructureFrench_horns', name?: string | null } | null> | null, trumpets?: Array<{ __typename: 'StructureTrumpets', name?: string | null } | null> | null, trombones?: Array<{ __typename: 'StructureTrombones', name?: string | null } | null> | null, tube?: Array<{ __typename: 'StructureTube', name?: string | null } | null> | null, drums?: Array<{ __typename: 'StructureDrums', name?: string | null } | null> | null };

export type ConductorsPartsFragment = { __typename?: 'Conductors', conductors?: Array<{ __typename: 'ConductorsConductors', photo?: string | null, name?: string | null, text?: string | null } | null> | null };

export type ConcertPartsFragment = { __typename?: 'Concert', name?: string | null, date?: string | null, time?: string | null, address?: string | null, conductor?: string | null, solists?: string | null, price?: string | null, description?: any | null };

export type GalleryPartsFragment = { __typename?: 'Gallery', sections?: Array<{ __typename: 'GallerySections', name?: string | null, items?: Array<{ __typename: 'GallerySectionsItems', url?: string | null } | null> | null } | null> | null };

export type ContactPartsFragment = { __typename?: 'Contact', email?: string | null, leadership?: { __typename: 'ContactLeadership', name?: string | null, phone?: string | null, email?: string | null } | null, practice?: { __typename: 'ContactPractice', text?: string | null, address?: string | null } | null };

export type GetHomeDocumentQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type GetHomeDocumentQuery = { __typename?: 'Query', getHomeDocument: { __typename?: 'HomeDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Home', title?: string | null } } };

export type GetHomeListQueryVariables = Exact<{ [key: string]: never; }>;


export type GetHomeListQuery = { __typename?: 'Query', getHomeList: { __typename?: 'HomeConnection', totalCount: number, edges?: Array<{ __typename?: 'HomeConnectionEdges', node?: { __typename?: 'HomeDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Home', title?: string | null } } | null } | null> | null } };

export type GetAboutDocumentQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type GetAboutDocumentQuery = { __typename?: 'Query', getAboutDocument: { __typename?: 'AboutDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'About', description?: any | null } } };

export type GetAboutListQueryVariables = Exact<{ [key: string]: never; }>;


export type GetAboutListQuery = { __typename?: 'Query', getAboutList: { __typename?: 'AboutConnection', totalCount: number, edges?: Array<{ __typename?: 'AboutConnectionEdges', node?: { __typename?: 'AboutDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'About', description?: any | null } } | null } | null> | null } };

export type GetStructureDocumentQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type GetStructureDocumentQuery = { __typename?: 'Query', getStructureDocument: { __typename?: 'StructureDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Structure', first_violins?: Array<{ __typename: 'StructureFirst_violins', name?: string | null } | null> | null, second_violins?: Array<{ __typename: 'StructureSecond_violins', name?: string | null } | null> | null, viols?: Array<{ __typename: 'StructureViols', name?: string | null } | null> | null, violoncellos?: Array<{ __typename: 'StructureVioloncellos', name?: string | null } | null> | null, basses?: Array<{ __typename: 'StructureBasses', name?: string | null } | null> | null, flutes?: Array<{ __typename: 'StructureFlutes', name?: string | null } | null> | null, oboes?: Array<{ __typename: 'StructureOboes', name?: string | null } | null> | null, clarinets?: Array<{ __typename: 'StructureClarinets', name?: string | null } | null> | null, bassoons?: Array<{ __typename: 'StructureBassoons', name?: string | null } | null> | null, french_horns?: Array<{ __typename: 'StructureFrench_horns', name?: string | null } | null> | null, trumpets?: Array<{ __typename: 'StructureTrumpets', name?: string | null } | null> | null, trombones?: Array<{ __typename: 'StructureTrombones', name?: string | null } | null> | null, tube?: Array<{ __typename: 'StructureTube', name?: string | null } | null> | null, drums?: Array<{ __typename: 'StructureDrums', name?: string | null } | null> | null } } };

export type GetStructureListQueryVariables = Exact<{ [key: string]: never; }>;


export type GetStructureListQuery = { __typename?: 'Query', getStructureList: { __typename?: 'StructureConnection', totalCount: number, edges?: Array<{ __typename?: 'StructureConnectionEdges', node?: { __typename?: 'StructureDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Structure', first_violins?: Array<{ __typename: 'StructureFirst_violins', name?: string | null } | null> | null, second_violins?: Array<{ __typename: 'StructureSecond_violins', name?: string | null } | null> | null, viols?: Array<{ __typename: 'StructureViols', name?: string | null } | null> | null, violoncellos?: Array<{ __typename: 'StructureVioloncellos', name?: string | null } | null> | null, basses?: Array<{ __typename: 'StructureBasses', name?: string | null } | null> | null, flutes?: Array<{ __typename: 'StructureFlutes', name?: string | null } | null> | null, oboes?: Array<{ __typename: 'StructureOboes', name?: string | null } | null> | null, clarinets?: Array<{ __typename: 'StructureClarinets', name?: string | null } | null> | null, bassoons?: Array<{ __typename: 'StructureBassoons', name?: string | null } | null> | null, french_horns?: Array<{ __typename: 'StructureFrench_horns', name?: string | null } | null> | null, trumpets?: Array<{ __typename: 'StructureTrumpets', name?: string | null } | null> | null, trombones?: Array<{ __typename: 'StructureTrombones', name?: string | null } | null> | null, tube?: Array<{ __typename: 'StructureTube', name?: string | null } | null> | null, drums?: Array<{ __typename: 'StructureDrums', name?: string | null } | null> | null } } | null } | null> | null } };

export type GetConductorsDocumentQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type GetConductorsDocumentQuery = { __typename?: 'Query', getConductorsDocument: { __typename?: 'ConductorsDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Conductors', conductors?: Array<{ __typename: 'ConductorsConductors', photo?: string | null, name?: string | null, text?: string | null } | null> | null } } };

export type GetConductorsListQueryVariables = Exact<{ [key: string]: never; }>;


export type GetConductorsListQuery = { __typename?: 'Query', getConductorsList: { __typename?: 'ConductorsConnection', totalCount: number, edges?: Array<{ __typename?: 'ConductorsConnectionEdges', node?: { __typename?: 'ConductorsDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Conductors', conductors?: Array<{ __typename: 'ConductorsConductors', photo?: string | null, name?: string | null, text?: string | null } | null> | null } } | null } | null> | null } };

export type GetConcertDocumentQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type GetConcertDocumentQuery = { __typename?: 'Query', getConcertDocument: { __typename?: 'ConcertDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Concert', name?: string | null, date?: string | null, time?: string | null, address?: string | null, conductor?: string | null, solists?: string | null, price?: string | null, description?: any | null } } };

export type GetConcertListQueryVariables = Exact<{ [key: string]: never; }>;


export type GetConcertListQuery = { __typename?: 'Query', getConcertList: { __typename?: 'ConcertConnection', totalCount: number, edges?: Array<{ __typename?: 'ConcertConnectionEdges', node?: { __typename?: 'ConcertDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Concert', name?: string | null, date?: string | null, time?: string | null, address?: string | null, conductor?: string | null, solists?: string | null, price?: string | null, description?: any | null } } | null } | null> | null } };

export type GetGalleryDocumentQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type GetGalleryDocumentQuery = { __typename?: 'Query', getGalleryDocument: { __typename?: 'GalleryDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Gallery', sections?: Array<{ __typename: 'GallerySections', name?: string | null, items?: Array<{ __typename: 'GallerySectionsItems', url?: string | null } | null> | null } | null> | null } } };

export type GetGalleryListQueryVariables = Exact<{ [key: string]: never; }>;


export type GetGalleryListQuery = { __typename?: 'Query', getGalleryList: { __typename?: 'GalleryConnection', totalCount: number, edges?: Array<{ __typename?: 'GalleryConnectionEdges', node?: { __typename?: 'GalleryDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Gallery', sections?: Array<{ __typename: 'GallerySections', name?: string | null, items?: Array<{ __typename: 'GallerySectionsItems', url?: string | null } | null> | null } | null> | null } } | null } | null> | null } };

export type GetContactDocumentQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type GetContactDocumentQuery = { __typename?: 'Query', getContactDocument: { __typename?: 'ContactDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Contact', email?: string | null, leadership?: { __typename: 'ContactLeadership', name?: string | null, phone?: string | null, email?: string | null } | null, practice?: { __typename: 'ContactPractice', text?: string | null, address?: string | null } | null } } };

export type GetContactListQueryVariables = Exact<{ [key: string]: never; }>;


export type GetContactListQuery = { __typename?: 'Query', getContactList: { __typename?: 'ContactConnection', totalCount: number, edges?: Array<{ __typename?: 'ContactConnectionEdges', node?: { __typename?: 'ContactDocument', id: string, sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, data: { __typename?: 'Contact', email?: string | null, leadership?: { __typename: 'ContactLeadership', name?: string | null, phone?: string | null, email?: string | null } | null, practice?: { __typename: 'ContactPractice', text?: string | null, address?: string | null } | null } } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  title
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  description
}
    `;
export const StructurePartsFragmentDoc = gql`
    fragment StructureParts on Structure {
  first_violins {
    __typename
    name
  }
  second_violins {
    __typename
    name
  }
  viols {
    __typename
    name
  }
  violoncellos {
    __typename
    name
  }
  basses {
    __typename
    name
  }
  flutes {
    __typename
    name
  }
  oboes {
    __typename
    name
  }
  clarinets {
    __typename
    name
  }
  bassoons {
    __typename
    name
  }
  french_horns {
    __typename
    name
  }
  trumpets {
    __typename
    name
  }
  trombones {
    __typename
    name
  }
  tube {
    __typename
    name
  }
  drums {
    __typename
    name
  }
}
    `;
export const ConductorsPartsFragmentDoc = gql`
    fragment ConductorsParts on Conductors {
  conductors {
    __typename
    photo
    name
    text
  }
}
    `;
export const ConcertPartsFragmentDoc = gql`
    fragment ConcertParts on Concert {
  name
  date
  time
  address
  conductor
  solists
  price
  description
}
    `;
export const GalleryPartsFragmentDoc = gql`
    fragment GalleryParts on Gallery {
  sections {
    __typename
    name
    items {
      __typename
      url
    }
  }
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  email
  leadership {
    __typename
    name
    phone
    email
  }
  practice {
    __typename
    text
    address
  }
}
    `;
export const GetHomeDocumentDocument = gql`
    query getHomeDocument($relativePath: String!) {
  getHomeDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...HomeParts
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const GetHomeListDocument = gql`
    query getHomeList {
  getHomeList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...HomeParts
        }
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const GetAboutDocumentDocument = gql`
    query getAboutDocument($relativePath: String!) {
  getAboutDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...AboutParts
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const GetAboutListDocument = gql`
    query getAboutList {
  getAboutList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...AboutParts
        }
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const GetStructureDocumentDocument = gql`
    query getStructureDocument($relativePath: String!) {
  getStructureDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...StructureParts
    }
  }
}
    ${StructurePartsFragmentDoc}`;
export const GetStructureListDocument = gql`
    query getStructureList {
  getStructureList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...StructureParts
        }
      }
    }
  }
}
    ${StructurePartsFragmentDoc}`;
export const GetConductorsDocumentDocument = gql`
    query getConductorsDocument($relativePath: String!) {
  getConductorsDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...ConductorsParts
    }
  }
}
    ${ConductorsPartsFragmentDoc}`;
export const GetConductorsListDocument = gql`
    query getConductorsList {
  getConductorsList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...ConductorsParts
        }
      }
    }
  }
}
    ${ConductorsPartsFragmentDoc}`;
export const GetConcertDocumentDocument = gql`
    query getConcertDocument($relativePath: String!) {
  getConcertDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...ConcertParts
    }
  }
}
    ${ConcertPartsFragmentDoc}`;
export const GetConcertListDocument = gql`
    query getConcertList {
  getConcertList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...ConcertParts
        }
      }
    }
  }
}
    ${ConcertPartsFragmentDoc}`;
export const GetGalleryDocumentDocument = gql`
    query getGalleryDocument($relativePath: String!) {
  getGalleryDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...GalleryParts
    }
  }
}
    ${GalleryPartsFragmentDoc}`;
export const GetGalleryListDocument = gql`
    query getGalleryList {
  getGalleryList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...GalleryParts
        }
      }
    }
  }
}
    ${GalleryPartsFragmentDoc}`;
export const GetContactDocumentDocument = gql`
    query getContactDocument($relativePath: String!) {
  getContactDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...ContactParts
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export const GetContactListDocument = gql`
    query getContactList {
  getContactList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...ContactParts
        }
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      getHomeDocument(variables: GetHomeDocumentQueryVariables, options?: C): Promise<{data: GetHomeDocumentQuery, variables: GetHomeDocumentQueryVariables, query: string}> {
        return requester<{data: GetHomeDocumentQuery, variables: GetHomeDocumentQueryVariables, query: string}, GetHomeDocumentQueryVariables>(GetHomeDocumentDocument, variables, options);
      },
    getHomeList(variables?: GetHomeListQueryVariables, options?: C): Promise<{data: GetHomeListQuery, variables: GetHomeListQueryVariables, query: string}> {
        return requester<{data: GetHomeListQuery, variables: GetHomeListQueryVariables, query: string}, GetHomeListQueryVariables>(GetHomeListDocument, variables, options);
      },
    getAboutDocument(variables: GetAboutDocumentQueryVariables, options?: C): Promise<{data: GetAboutDocumentQuery, variables: GetAboutDocumentQueryVariables, query: string}> {
        return requester<{data: GetAboutDocumentQuery, variables: GetAboutDocumentQueryVariables, query: string}, GetAboutDocumentQueryVariables>(GetAboutDocumentDocument, variables, options);
      },
    getAboutList(variables?: GetAboutListQueryVariables, options?: C): Promise<{data: GetAboutListQuery, variables: GetAboutListQueryVariables, query: string}> {
        return requester<{data: GetAboutListQuery, variables: GetAboutListQueryVariables, query: string}, GetAboutListQueryVariables>(GetAboutListDocument, variables, options);
      },
    getStructureDocument(variables: GetStructureDocumentQueryVariables, options?: C): Promise<{data: GetStructureDocumentQuery, variables: GetStructureDocumentQueryVariables, query: string}> {
        return requester<{data: GetStructureDocumentQuery, variables: GetStructureDocumentQueryVariables, query: string}, GetStructureDocumentQueryVariables>(GetStructureDocumentDocument, variables, options);
      },
    getStructureList(variables?: GetStructureListQueryVariables, options?: C): Promise<{data: GetStructureListQuery, variables: GetStructureListQueryVariables, query: string}> {
        return requester<{data: GetStructureListQuery, variables: GetStructureListQueryVariables, query: string}, GetStructureListQueryVariables>(GetStructureListDocument, variables, options);
      },
    getConductorsDocument(variables: GetConductorsDocumentQueryVariables, options?: C): Promise<{data: GetConductorsDocumentQuery, variables: GetConductorsDocumentQueryVariables, query: string}> {
        return requester<{data: GetConductorsDocumentQuery, variables: GetConductorsDocumentQueryVariables, query: string}, GetConductorsDocumentQueryVariables>(GetConductorsDocumentDocument, variables, options);
      },
    getConductorsList(variables?: GetConductorsListQueryVariables, options?: C): Promise<{data: GetConductorsListQuery, variables: GetConductorsListQueryVariables, query: string}> {
        return requester<{data: GetConductorsListQuery, variables: GetConductorsListQueryVariables, query: string}, GetConductorsListQueryVariables>(GetConductorsListDocument, variables, options);
      },
    getConcertDocument(variables: GetConcertDocumentQueryVariables, options?: C): Promise<{data: GetConcertDocumentQuery, variables: GetConcertDocumentQueryVariables, query: string}> {
        return requester<{data: GetConcertDocumentQuery, variables: GetConcertDocumentQueryVariables, query: string}, GetConcertDocumentQueryVariables>(GetConcertDocumentDocument, variables, options);
      },
    getConcertList(variables?: GetConcertListQueryVariables, options?: C): Promise<{data: GetConcertListQuery, variables: GetConcertListQueryVariables, query: string}> {
        return requester<{data: GetConcertListQuery, variables: GetConcertListQueryVariables, query: string}, GetConcertListQueryVariables>(GetConcertListDocument, variables, options);
      },
    getGalleryDocument(variables: GetGalleryDocumentQueryVariables, options?: C): Promise<{data: GetGalleryDocumentQuery, variables: GetGalleryDocumentQueryVariables, query: string}> {
        return requester<{data: GetGalleryDocumentQuery, variables: GetGalleryDocumentQueryVariables, query: string}, GetGalleryDocumentQueryVariables>(GetGalleryDocumentDocument, variables, options);
      },
    getGalleryList(variables?: GetGalleryListQueryVariables, options?: C): Promise<{data: GetGalleryListQuery, variables: GetGalleryListQueryVariables, query: string}> {
        return requester<{data: GetGalleryListQuery, variables: GetGalleryListQueryVariables, query: string}, GetGalleryListQueryVariables>(GetGalleryListDocument, variables, options);
      },
    getContactDocument(variables: GetContactDocumentQueryVariables, options?: C): Promise<{data: GetContactDocumentQuery, variables: GetContactDocumentQueryVariables, query: string}> {
        return requester<{data: GetContactDocumentQuery, variables: GetContactDocumentQueryVariables, query: string}, GetContactDocumentQueryVariables>(GetContactDocumentDocument, variables, options);
      },
    getContactList(variables?: GetContactListQueryVariables, options?: C): Promise<{data: GetContactListQuery, variables: GetContactListQueryVariables, query: string}> {
        return requester<{data: GetContactListQuery, variables: GetContactListQueryVariables, query: string}, GetContactListQueryVariables>(GetContactListDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { staticRequest } from 'tinacms'
const requester: (doc: any, vars?: any, options?: any) => Promise<any> = async (
  doc,
  vars,
  _options
) => {
  let data = {}
  try {
    data = await staticRequest({
      query: doc,
      variables: vars,
    })
  } catch (e) {
    // swallow errors related to document creation
    console.warn('Warning: There was an error when fetching data')
    console.warn(e)
  }

  return { data, query: doc, variables: vars || {} }
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = ()=>getSdk(requester)

